name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: wget
      uses: wei/wget@v1
      with:
        args: https://sourceforge.net/projects/sdcc/files/sdcc-linux-amd64/4.0.0/sdcc-4.0.0-amd64-unknown-linux2.5.tar.bz2
    - run: |
        tar xvjf sdcc-4.0.0-amd64-unknown-linux2.5.tar.bz2
        cd sdcc-4.0.0 
        sudo cp -r * /usr/local
      
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        sudo apt install python3-pip
        sudo apt-get install python3.9-venv
        python3.9 -m pip install pillow
    - name: Display Python version
      run: python --version    
    - name: make clean
      run: make clean
    - name: make game
      run: sudo make game
