name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: sdcc download and install
    - run: |
        wget https://sourceforge.net/projects/sdcc/files/sdcc-linux-amd64/4.0.0/sdcc-4.0.0-amd64-unknown-linux2.5.tar.bz2 |
        tar xvjf sdcc-4.0.0-amd64-unknown-linux2.5.tar.bz2 |
        cd sdcc-4.0.0 
        cp -r * /usr/local
    - name: make clean
      run: make clean
    - name: make game
      run: make game
