name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - name: sdcc
      uses: wei/wget@v1
      with:
        args: https://sourceforge.net/projects/sdcc/files/sdcc-linux-amd64/4.0.0/sdcc-4.0.0-amd64-unknown-linux2.5.tar.bz2
    - run: |
        tar xvjf sdcc-4.0.0-amd64-unknown-linux2.5.tar.bz2
        cd sdcc-4.0.0 
        sudo cp -r * /usr/local
    - name: hex2bin
      uses: wei/wget@v1
      with:
        args: https://sourceforge.net/projects/hex2bin
    - run: |
        sudo cp -r hex2bin /usr/local/bin
    - name: Disark
      uses: wei/wget@v1
      with:
        args: http://www.julien-nevo.com/arkostracker/release/linux64/Arkos%20Tracker%202%20Linux64.zip
    - run: |
        unzip Arkos%20Tracker%202%20Linux64.zip
        sudo cp -r "Arkos Tracker 2/tools/Disark" /usr/local/bin
      
    - uses: actions/setup-python@v3
      with:
        python-version: 3.9  
    - uses: actions/checkout@v3
    - name: green build
      run: |
        sudo apt install python3-pip
        python3.9 -m pip install pillow
        pip list
        python --version    
        make clean
        sudo make game
